packages: []

catalogs:
  build:
    '@nuxt/devtools': ^2.6.2
    '@nuxt/eslint': ^1.5.1
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.1
    '@unocss/eslint-config': ^66.3.2
    '@unocss/nuxt': ^66.3.2
    '@vite-pwa/nuxt': ^1.0.4
    '@vueuse/nuxt': ^13.5.0
    nuxt: ^3.17.6
    unocss: ^66.3.2
    unplugin: ^2.3.5
    vite: ^7.0.0
  dev:
    '@antfu/eslint-config': ^4.16.2
    eslint: ^9.30.1
    eslint-plugin-format: ^1.0.1
    typescript: ^5.8.3
    vue-tsc: ^2.2.12
  frontend:
    '@vueuse/core': ^13.5.0
    pinia: ^3.0.3
    vue: ^3.5.17
  icons:
    '@iconify-json/carbon': ^1.2.10
    '@iconify-json/simple-icons': ^1.2.41
    '@iconify-json/twemoji': ^1.2.2

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
